---
- name: this playbook creates new user
  hosts: all
  become: true
    #vars:
    #user: kate
  vars_files: 
    - /home/ansadmin/users.yml 
  tasks:
  - name: creatng user {{ user }}
    user:
      name: "{{ user }}"
