---
- name: this playbook installs packages
  hosts: webservers
  become: true
  tasks: 
  - name: install package
    yum: 
      name: ['git', 'make', 'gcc', 'telnet', 'gzip'] 
      state: installed
