---
- name: this playbook installs apache httpd
  hosts: all
  become: true
  tasks:
  - name: install package RHEL
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start httpd service
  
  - name: install package Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2
  
  - name: copy new index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0664    

  handlers:  
  - name: start httpd service
    service:
      name: httpd
      state: started
      ignore_errors: yes

  - name: start apache2
    service:
      name: apache2
      state: started
      ignore_errors: yes
