---
- name: this playbook uninstalls apache httpd
  hosts: all 
  become: true
  tasks: 
  - name: stop httpd 
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"
    notify: uninstall httpd
      #ignore_errors: yes

  - name: stop apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"
    notify: uninstall apache2
      #ignore_errors: yes

  handlers:    
  - name: uninstall httpd
    yum:
      name: httpd
      state: removed

  - name: uninstall apache2
    apt: 
      name: apache2
      state: absent 

