---
- name: this playbook installs apache httpd
  hosts: all
  become: true
  tasks:
  - name: install package RHEL
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache

  - name: install package Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache

  - name: start httpd service
    service:
      name: httpd
      state: started
    tags: start_apache

  - name: start apache2
    service:
      name: apache2
      state: started
    tags: start_apache
